<a href="https://colab.research.google.com/github/MaicolHernandez33/Actividad1/blob/main/Actividad1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('1.1.6. Archivo para actividad práctica.csv')
df.head(15)

,S.NO,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
0,1,Mike Tyson,USA,1,NaN,boxing,1990,28.6
1,2,Buster Douglas,USA,2,NaN,boxing,1990,26.0
2,3,Sugar Ray Leonard,USA,3,NaN,boxing,1990,13.0
3,4,Ayrton Senna,Brazil,4,NaN,auto racing,1990,10.0
4,5,Alain Prost,France,5,NaN,auto racing,1990,9.0
5,6,Jack Nicklaus,USA,6,NaN,golf,1990,8.6
6,7,Greg Norman,Australia,7,NaN,golf,1990,8.5
7,8,Michael Jordan,USA,8,NaN,basketball,1990,8.1
8,9,Arnold Palmer,USA,8,NaN,golf,1990,8.1
9,10,Evander Holyfield,USA,8,NaN,boxing,1990,8.1
10,11,Evander Holyfield,USA,1,8,boxing,1991,60.5
11,12,Mike Tyson,USA,2,1,boxing,1991,31.5
12,13,Michael Jordan,USA,3,8,basketball,1991,16.0
13,14,George Foreman,USA,4,>30,boxing,1991,14.5
14,15,Ayrton Senna,Brazil,5,4,auto racing,1991,13.0

1. Cargue los datos en un dataframe
2. Identificar el tipo de datos de cada variable.
3. Calcular estadísticas básicas para cada variable. Sea de posición, dispersión y tendencia central. Para el caso de variables categóricas
calcule la moda.
4. Transforme la variable “earnings” en una variable categórica implementando intervalos de clase. Calcule la frecuencia de cada clase.
5. Conteste las siguientes preguntas:
a) ¿Quién es la persona que más dinero ganó en un año?
b) ¿Cuál es el deporte que más se repite dentro de la lista?
c) ¿Cuál es el deporte donde más dinero se gana?
d) Si quisiera apostar a un jugador de Basketball según su ranking. ¿A cuál debería apostar?
e) ¿Para qué áreas de negocio puede ser útil el análisis de este dataset? ¿Qué decisiones puede ayudar a tomar?
6. Entregue conclusiones sobre lo desarrollado. Comente los descubrimientos que más le sorprendieron, lo que más le costó y qué
otra información le gustaría extraer de los datos trabajados

Tipos de dato:  
  
- Name: Cualitativo nominal
- Nationality: Cualitativo nominal
- Current Rank: Cuantitativa discreta
- Previous Year Rank: Cuantitativa discreta
- Sport: Cualitativo nominal
- Year: Cuantitativa discreta
- earnings ($ million): Cuantitativa continua

## Variables Categóricas

In [8]:
df['Name'].mode()

0    Michael Jordan
1       Tiger Woods
Name: Name, dtype: object

En este caso la moda serian 2, Michel Jordan y Tiger Woods siendo los nombres que más se repetinen en la bd.

In [11]:
df['Nationality'].mode()

0    USA
Name: Nationality, dtype: object

Para la nacionalidad la moda seria USA siendo el que más se repite de la naciodanidad de los deportistas.

In [13]:
df['Sport'].mode()

0    Basketball
Name: Sport, dtype: object

La moda de la categoría 'Sport' es Basketball

In [18]:
df['Previous Year Rank'].mode()

0    >10
Name: Previous Year Rank, dtype: object

La moda de 'Previous Year Rank' es ">10", indicando que la mayor frecuencia corresponde a deportistas que en el año anterior estaban fuera del top 10 del ranking.
  
De esta categoría solo hice la moda ya que aunque tenia valores numéricos también tenía textos o datos como >30, siendo de momento dificil sacar estadisticas basicas de aca ya que habria que limpiar o transformar algunos datos como los NaN o >30.

## Variables númericas

In [33]:
print(f"Media: {df['Current Rank'].mean():.2f}")
print(f"Mediana: {df['Current Rank'].median():.2f}")
print(f"Moda: {df['Current Rank'].mode()[0]:.2f}")
print(f"Desviación estándar: {df['Current Rank'].std():.2f}")
print(f"Varianza: {df['Current Rank'].var():.2f}")
print(f"Rango: {df['Current Rank'].max() - df['Current Rank'].min():.2f}")
print(f"Mínimo: {df['Current Rank'].min():.2f}")
print(f"Máximo: {df['Current Rank'].max():.2f}")

Media: 5.45
Mediana: 5.0
Moda: 0    9
Name: Current Rank, dtype: int64
2.8509950469046905
8.128172757475078
9
1
10